### ISSUE TITLE
Dynamic_filter using ajax

### ISSUE THREAD

**Issue by ghost** [djangopy-org/dynamic_filter#1]
[django ajax dynamic filter.zip](https://github.com/djangopy-org/dynamic_filter/files/3153484/django.ajax.dynamic.filter.zip)

The API is working, but when html is rendered the dropdowns don't provide the list of region/status and none of the available objects are displayed as shown in the picture attached within the file.

**Comment by jai-singhal** [comment]
Hello Austin,
All seem to be fine. Can you please show the console logs in Developer tools of your browser, also attach the logs from the command prompt of Django Server?
Meanwhile, follow this guide if not already https://djangopy.org/learn/dynamically-filter-queryset-with-ajax-and-drf

**Comment by nitheshhegde** [comment]
Hi Jai Singhal, 
I'm Austin's friend.

**Here are the console logs in Developer tools:** 
ReferenceError: $ is not defined wine.js:3:1
    <anonymous> http://localhost:8000/static/aspire/wine.js:3
[Exception... "Favicon at "http://localhost:8000/static/aspire/images/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 199"  data: no]
    onStopRequest resource:///modules/FaviconLoader.jsm:199
    next self-hosted:1210
TypeError: document.getElementById(...) is null emicalc-loader.min.js:6:99
    onload https://emicalculator.net/widget/2.0/js/emicalc-loader.min.js:6


**Here are the logs from the command prompt :** 
<QuerySet [<Property: Pyramid Elevation>, <Property: Pyramid Carnations>, <Prope
rty: Pyramid Watsonia>, <Property: Salapuria Adonis>]>
C:\Users\Nithesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\res
t_framework\pagination.py:198: UnorderedObjectListWarning: Pagination may yield
inconsistent results with an unordered object_list: <class 'aspire.models.Proper
ty'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[08/May/2019 09:09:14] "GET /aspire/featured-projects/ HTTP/1.1" 200 21320
Not Found: /aspire/featured-projects/details.css
[08/May/2019 09:09:14] "GET /aspire/featured-projects/details.css HTTP/1.1" 404
5743
Not Found: /aspire/featured-projects/details.css
[08/May/2019 09:09:14] "GET /aspire/featured-projects/details.css HTTP/1.1" 404
5743

**Comment by jai-singhal** [comment]
Have you included the jquery library. Try changing the version of jquery

**Comment by nitheshhegde** [comment]
Yes, I have added this. 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
Sometimes I see "No results found" as a message and if I change jquery version, I see "Something went wrong" message.

**Comment by jai-singhal** [comment]
There is something wrong in writing the Javascript, please check your Javascript code and try  to remove the errors from console log.

**Comment by nitheshhegde** [comment]
Hi Jai Singhal,

Dropdown is working fine now. It displays all the fields in the database.
But content is not getting displayed below. 

In Console it says, 404 not found for this URL
http://localhost:8000/aspire/featured-projects/?region=&status=&format=json

But I'm getting success for these 2 urls, 
http://localhost:8000/aspire/ajax/area/
http://localhost:8000/aspire/ajax/status/

**Comment by jai-singhal** [comment]
Check the endpoint of the api which you have created, and try using POSTMAN for validating the API

**Comment by jai-singhal** [comment]
I am closing this issue. If you have furthermore queries, feel free to comment on https://djangopy.org/learn/dynamically-filter-queryset-with-ajax-and-drf
